[build-system]
requires = ["maturin-0.8.3-py3-none-manylinux1_x86_64.whl"]
build-backend = "maturin"

[project]
name = "MRzeroCore"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[tool.maturin]
python-source = "python"
name = "MRzeroCore._prepass"
