[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project]
name = "MRzeroCore"
requires-python = ">=3.7"
license = "AGPL-3.0-only"
repository = "https://gitlab.cs.fau.de/mrzero/MRzero-Core"
documentation = "https://mrzerocore.readthedocs.io"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "torch>=1.12",
    "pypulseq",
    "matplotlib",
    "scipy"
]

[tool.maturin]
profile = "release"
strip = true
module-name = "MRzeroCore._prepass"
python-source = "python"
